export default [
  {
    id: 1,
    name: "Wireless Mouse",
    description: "A high-precision wireless mouse with ergonomic design.",
    price: 29.99,
    category: "Electronics",
    stock: 150,
  },
  {
    id: 2,
    name: "Bluetooth Headphones",
    description: "Noise-cancelling over-ear headphones with long battery life.",
    price: 89.99,
    category: "Electronics",
    stock: 75,
  },
  {
    id: 3,
    name: "Smartphone Stand",
    description: "Adjustable stand for smartphones and tablets.",
    price: 14.99,
    category: "Accessories",
    stock: 200,
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with customizable keys.",
    price: 119.99,
    category: "Electronics",
    stock: 50,
  },
  {
    id: 5,
    name: "USB-C Hub",
    description: "Multi-port USB-C hub with HDMI, USB 3.0, and SD card reader.",
    price: 39.99,
    category: "Accessories",
    stock: 100,
  },
];
